import * as THREE from "three"
import JSZip from "jszip"
import type { HookParams } from "./hookGeometry"

/** Exports a BufferGeometry as a binary STL file and triggers download. */
export function exportSTL(geometry: THREE.BufferGeometry, filename = "gitternett_krok.stl") {
  const posAttr = geometry.getAttribute("position") as THREE.BufferAttribute
  const triangleCount = posAttr.count / 3

  const buffer = new ArrayBuffer(84 + triangleCount * 50)
  const view = new DataView(buffer)

  // 80-byte header (unused, zeroed)
  for (let i = 0; i < 80; i++) view.setUint8(i, 0)
  view.setUint32(80, triangleCount, true)

  const vA = new THREE.Vector3()
  const vB = new THREE.Vector3()
  const vC = new THREE.Vector3()
  const normal = new THREE.Vector3()
  const edge1 = new THREE.Vector3()
  const edge2 = new THREE.Vector3()

  let offset = 84
  for (let i = 0; i < triangleCount; i++) {
    const i3 = i * 3
    vA.fromBufferAttribute(posAttr, i3)
    vB.fromBufferAttribute(posAttr, i3 + 1)
    vC.fromBufferAttribute(posAttr, i3 + 2)

    edge1.subVectors(vB, vA)
    edge2.subVectors(vC, vA)
    normal.crossVectors(edge1, edge2).normalize()

    // Normal vector (3 × float32)
    view.setFloat32(offset, normal.x, true); offset += 4
    view.setFloat32(offset, normal.y, true); offset += 4
    view.setFloat32(offset, normal.z, true); offset += 4

    // Three vertices (9 × float32)
    for (const v of [vA, vB, vC]) {
      view.setFloat32(offset, v.x, true); offset += 4
      view.setFloat32(offset, v.y, true); offset += 4
      view.setFloat32(offset, v.z, true); offset += 4
    }

    // Attribute byte count (uint16, always 0)
    view.setUint16(offset, 0, true); offset += 2
  }

  triggerDownload(buffer, filename, "model/stl")
}

/**
 * Exports the geometry as a .3mf file (a ZIP archive containing an OBJ-style
 * XML mesh plus the required 3MF relationship and content-type files).
 */
export async function export3MF(
  geometry: THREE.BufferGeometry,
  filename = "gitternett_krok.3mf",
  params?: HookParams,
) {
  const posAttr = geometry.getAttribute("position") as THREE.BufferAttribute
  const triangleCount = posAttr.count / 3

  // Build vertex list and deduplicated index list
  const vertices: THREE.Vector3[] = []
  const triangles: [number, number, number][] = []
  const vertexMap = new Map<string, number>()

  function addVertex(v: THREE.Vector3): number {
    const key = `${v.x.toFixed(4)},${v.y.toFixed(4)},${v.z.toFixed(4)}`
    const existing = vertexMap.get(key)
    if (existing !== undefined) return existing
    const idx = vertices.length
    vertexMap.set(key, idx)
    vertices.push(v.clone())
    return idx
  }

  const vA = new THREE.Vector3()
  const vB = new THREE.Vector3()
  const vC = new THREE.Vector3()
  for (let i = 0; i < triangleCount; i++) {
    const i3 = i * 3
    vA.fromBufferAttribute(posAttr, i3)
    vB.fromBufferAttribute(posAttr, i3 + 1)
    vC.fromBufferAttribute(posAttr, i3 + 2)
    triangles.push([addVertex(vA), addVertex(vB), addVertex(vC)])
  }

  // Build the 3D model XML
  const verticesXml = vertices
    .map((v) => `      <vertex x="${v.x.toFixed(4)}" y="${v.y.toFixed(4)}" z="${v.z.toFixed(4)}" />`)
    .join("\n")

  const trianglesXml = triangles
    .map(([a, b, c]) => `      <triangle v1="${a}" v2="${b}" v3="${c}" />`)
    .join("\n")

  const paramComment = params
    ? `<!-- Generated by gitternett-krok. Params: ${JSON.stringify(params)} -->\n  `
    : ""

  const modelXml = `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xml:lang="en-US"
  xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  ${paramComment}<resources>
    <object id="1" type="model">
      <mesh>
        <vertices>
${verticesXml}
        </vertices>
        <triangles>
${trianglesXml}
        </triangles>
      </mesh>
    </object>
  </resources>
  <build>
    <item objectid="1" />
  </build>
</model>`

  const relsXml = `<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Target="/3D/model.model"
    Id="rel0"
    Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel" />
</Relationships>`

  const contentTypesXml = `<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml" />
  <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml" />
</Types>`

  const zip = new JSZip()
  zip.file("3D/model.model", modelXml)
  zip.file("_rels/.rels", relsXml)
  zip.file("[Content_Types].xml", contentTypesXml)

  const blob = await zip.generateAsync({ type: "blob", mimeType: "application/vnd.ms-package.3dmanufacturing-3dmodel+xml" })
  const arrayBuffer = await blob.arrayBuffer()
  triggerDownload(arrayBuffer, filename, "application/vnd.ms-package.3dmanufacturing-3dmodel+xml")
}

function triggerDownload(buffer: ArrayBuffer, filename: string, mimeType: string) {
  const blob = new Blob([buffer], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
